# Generated by Django 5.0.6 on 2024-06-11 11:40

import backend.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image_path',
            field=models.FileField(blank=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='pdf_path',
            field=models.FileField(blank=True, upload_to='pdfs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='video_path',
            field=models.FileField(blank=True, upload_to='videos/', validators=[backend.models.validate_video_file_extension]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='video_stream_path',
            field=models.FileField(blank=True, upload_to='videos/', validators=[backend.models.validate_video_file_extension]),
        ),
    ]
