# Generated by Django 5.0.6 on 2024-06-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_recipe_image_path_alter_recipe_pdf_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image_path',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='pdf_path',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='video_path',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='video_stream_path',
        ),
        migrations.AddField(
            model_name='recipe',
            name='image_data',
            field=models.BinaryField(blank=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='pdf_data',
            field=models.BinaryField(blank=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='video_data',
            field=models.BinaryField(blank=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='video_stream_data',
            field=models.BinaryField(blank=True),
        ),
    ]
